module.exports = {
	vm: require('vm'),
	io: require('io'),
	fs: require('fs'),
	mq: require("mq"),
	db: require('db'),
	rpc: require('rpc'),
	http: require('http'),
	encoding: require('encoding'),
	coroutine: require('coroutine'),
	uuid: require('uuid'),
	assert: require('assert'),
	gd: require("gd"),
	hash: require("hash"),
	test: require("test"),
	net: require("net"),
	process: require("process"),
	os: require("os"),
	util: require("util"),
	path: require("path"),
	ssl: require("ssl"),
	xml: require("xml"),
	profiler: require("profiler"),
	crypto: require("crypto"),
	websocket: require("websocket"),
	base64: require("base64")
}